# Content\-Based Filtering

In [1]:
import pandas
movies = pandas.read_csv("movies.csv", sep=",")

In [2]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words="english")
movies["overview"] = movies["overview"].fillna("")

In [4]:
tfidf_matrix = tfidf.fit_transform(movies["overview"])

In [5]:
pandas.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zuckerberg,zula,zuzu,zyklon,æon,éloigne,émigré,été,única,über
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Similarity matrix

In [6]:
from sklearn.metrics.pairwise import linear_kernel
similarity_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)

In [7]:
similarity_matrix

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.01488159, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02160533, 0.01488159, ..., 1.        , 0.01609091,
        0.00701914],
       [0.        , 0.        , 0.        , ..., 0.01609091, 1.        ,
        0.01171696],
       [0.        , 0.        , 0.        , ..., 0.00701914, 0.01171696,
        1.        ]], shape=(4803, 4803))

### Find the most similar movies to a certain movie

In [8]:
movie_title = "John Carter"

In [9]:
idx = movies.loc[movies["title"]==movie_title].index[0]
idx

np.int64(4)

In [10]:
scores = list(enumerate(similarity_matrix[idx]))
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.033368675996424305)),
 (2, np.float64(0.0)),
 (3, np.float64(0.010433403719159351)),
 (4, np.float64(0.9999999999999998)),
 (5, np.float64(0.0)),
 (6, np.float64(0.009339192776152496)),
 (7, np.float64(0.037407042075763064)),
 (8, np.float64(0.0)),
 (9, np.float64(0.01714819056424443)),
 (10, np.float64(0.02015372184154536)),
 (11, np.float64(0.0)),
 (12, np.float64(0.03178129553727139)),
 (13, np.float64(0.0)),
 (14, np.float64(0.010712515993695904)),
 (15, np.float64(0.0)),
 (16, np.float64(0.045257098111540495)),
 (17, np.float64(0.020358841382635908)),
 (18, np.float64(0.016907757517459005)),
 (19, np.float64(0.016254574057966483)),
 (20, np.float64(0.00914487577692374)),
 (21, np.float64(0.01727519014981104)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.01651050909357743)),
 (25, np.float64(0.0)),
 (26, np.float64(0.0538746515929863)),
 (27, np.float64(0.05231039324590807)),
 (28, np.float64(0.025467489988822038)),
 (29, np.float64(0.016102329289885736)),
 (30, np.float64(0.0)),
 (31, np.float64(0.01112130271029684)),
 (32, np.float64(0.021415531407536444)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.015826523804524963)),
 (36, np.float64(0.0381036148024992)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.02124047042069265)),
 (40, np.float64(0.00768676619264308)),
 (41, np.float64(0.01978947253021744)),
 (42, np.float64(0.0)),
 (43, np.float64(0.015863240253729538)),
 (44, np.float64(0.0)),
 (45, np.float64(0.022783108397171153)),
 (46, np.float64(0.08574401380341932)),
 (47, np.float64(0.05837115580794347)),
 (48, np.float64(0.027291542501988043)),
 (49, np.float64(0.006661619072989001)),
 (50, np.float64(0.05348134003905951)),
 (51, np.float64(0.020303156755951995)),
 (52, np.float64(0.0200156467845625)),
 (53, np.float64(0.009283858002248853)),
 (54, np.float64(0.055073031440828375)),
 (55, np.float64(0.0)),
 (56, np.float64(0.019705548314540633)),
 (57, np.float64(0.0)),
 (58, np.float64(0.054437289544783836)),
 (59, np.float64(0.014107530611723554)),
 (60, np.float64(0.0)),
 (61, np.float64(0.0)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.023498148063470496)),
 (65, np.float64(0.009805867807909803)),
 (66, np.float64(0.0)),
 (67, np.float64(0.019190706170422227)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.01094440728890874)),
 (71, np.float64(0.0069811676473432675)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.0)),
 (75, np.float64(0.022943142552820633)),
 (76, np.float64(0.04563868300474624)),
 (77, np.float64(0.01613816783918202)),
 (78, np.float64(0.0)),
 (79, np.float64(0.025760454420038537)),
 (80, np.float64(0.0)),
 (81, np.float64(0.023055502664015293)),
 (82, np.float64(0.03199363546220082)),
 (83, np.float64(0.028302134677120096)),
 (84, np.float64(0.015367708891529573)),
 (85, np.float64(0.07927219338261442)),
 (86, np.float64(0.006837763027138118)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.0)),
 (91, np.float64(0.06511318345155809)),
 (92, np.float64(0.019392953319592822)),
 (93, np.float64(0.014362368494416106)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.018148157421771442)),
 (98, np.float64(0.026230631433396143)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.008401329648238235)),
 (102, np.float64(0.008264600510095794)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.04975088891450889)),
 (108, np.float64(0.043752278061972745)),
 (109, np.float64(0.00904550886236454)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.008616077306773266)),
 (113, np.float64(0.0232436032763467)),
 (114, np.float64(0.0)),
 (115, np.float64(0.04296474509718628)),
 (116, np.float64(0.006845348430513409)),
 (117, np.float64(0.02383924013893402)),
 (118, np.float64(0.004307772202327974)),
 (119, np.float64(0.0)),
 (120, np.float64(0.02063396385983972)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.017118286549121477)),
 (124, np.float64(0.0)),
 (125, np.float64(0.0052726074946179025)),
 (126, np.float64(0.0)),
 (127, np.float64(0.06404845195093839)),
 (128, np.float64(0.014785526097967284)),
 (129, np.float64(0.016373173519004035)),
 (130, np.float64(0.0)),
 (131, np.float64(0.013247495222260349)),
 (132, np.float64(0.016986814622034045)),
 (133, np.float64(0.009013912737246)),
 (134, np.float64(0.0)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.007624305016523995)),
 (138, np.float64(0.0)),
 (139, np.float64(0.0)),
 (140, np.float64(0.014621772405641194)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.006441374367745254)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.011442209453330259)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0)),
 (149, np.float64(0.0)),
 (150, np.float64(0.014514909084696942)),
 (151, np.float64(0.0)),
 (152, np.float64(0.0337894127869508)),
 (153, np.float64(0.0)),
 (154, np.float64(0.020238158756250166)),
 (155, np.float64(0.05465599273472925)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.06136006069574057)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0310376418629274)),
 (161, np.float64(0.0)),
 (162, np.float64(0.05810181561753072)),
 (163, np.float64(0.02455765274889435)),
 (164, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0)),
 (168, np.float64(0.01866531692929332)),
 (169, np.float64(0.06572494101819237)),
 (170, np.float64(0.014262203354444069)),
 (171, np.float64(0.020213553025880373)),
 (172, np.float64(0.0)),
 (173, np.float64(0.006426217684023491)),
 (174, np.float64(0.044059407675698686)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.009456290973925852)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.00592115948559236)),
 (183, np.float64(0.0)),
 (184, np.float64(0.014890046218071499)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.021570096830354435)),
 (191, np.float64(0.0)),
 (192, np.float64(0.04264162048414869)),
 (193, np.float64(0.014649147138545352)),
 (194, np.float64(0.0)),
 (195, np.float64(0.02434986534338656)),
 (196, np.float64(0.0)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.04573250153848858)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.03950100817441227)),
 (208, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.00805350235878616)),
 (212, np.float64(0.006514578034920522)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.0)),
 (221, np.float64(0.0)),
 (222, np.float64(0.017817525091440814)),
 (223, np.float64(0.02469657647746403)),
 (224, np.float64(0.012662616613306298)),
 (225, np.float64(0.014414400616726329)),
 (226, np.float64(0.0)),
 (227, np.float64(0.03220763022607363)),
 (228, np.float64(0.05095192690216123)),
 (229, np.float64(0.0)),
 (230, np.float64(0.02623367394148595)),
 (231, np.float64(0.014442290617753284)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.015145778094171853)),
 (235, np.float64(0.0)),
 (236, np.float64(0.020263192301588864)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0)),
 (241, np.float64(0.0067722890129990896)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.008711826055257733)),
 (246, np.float64(0.04171799726689648)),
 (247, np.float64(0.0)),
 (248, np.float64(0.014326342152548341)),
 (249, np.float64(0.0)),
 (250, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.02265922530400015)),
 (254, np.float64(0.006650792688227934)),
 (255, np.float64(0.012896368470763373)),
 (256, np.float64(0.02615391867618884)),
 (257, np.float64(0.030584604510354278)),
 (258, np.float64(0.003687806578639362)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.020104879387202026)),
 (262, np.float64(0.03546421485928934)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (266, np.float64(0.027922856347770603)),
 (267, np.float64(0.0)),
 (268, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.05289174055081866)),
 (271, np.float64(0.01774986014471247)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.019012012076864985)),
 (276, np.float64(0.02210070952010449)),
 (277, np.float64(0.005171953174037606)),
 (278, np.float64(0.02620492372756335)),
 (279, np.float64(0.0320445184668943)),
 (280, np.float64(0.013066707226628685)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.02551952695772625)),
 (287, np.float64(0.0)),
 (288, np.float64(0.013393761102071822)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.009622490529342706)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.059721269746251145)),
 (295, np.float64(0.013850948453916684)),
 (296, np.float64(0.0069639065859347996)),
 (297, np.float64(0.00935590260380906)),
 (298, np.float64(0.008486495818406884)),
 (299, np.float64(0.0)),
 (300, np.float64(0.03179698829721199)),
 (301, np.float64(0.0)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.03206725478560125)),
 (305, np.float64(0.03578394005663959)),
 (306, np.float64(0.007726185544930469)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.01399893758248774)),
 (311, np.float64(0.01324690348881613)),
 (312, np.float64(0.0)),
 (313, np.float64(0.032145106599792105)),
 (314, np.float64(0.0)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0782683431858148)),
 (323, np.float64(0.019866852649844356)),
 (324, np.float64(0.00603221501979096)),
 (325, np.float64(0.009715822571524414)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.02593549675040616)),
 (332, np.float64(0.0)),
 (333, np.float64(0.008838459012222235)),
 (334, np.float64(0.02363266602696133)),
 (335, np.float64(0.0)),
 (336, np.float64(0.00994266056124025)),
 (337, np.float64(0.025455855411282504)),
 (338, np.float64(0.0)),
 (339, np.float64(0.01745919496268492)),
 (340, np.float64(0.0)),
 (341, np.float64(0.020089065896757703)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.02207015132799061)),
 (345, np.float64(0.09079218287485014)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.0)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.02388360180558951)),
 (353, np.float64(0.0)),
 (354, np.float64(0.03257507459063306)),
 (355, np.float64(0.01398296085574484)),
 (356, np.float64(0.023825116200832504)),
 (357, np.float64(0.0)),
 (358, np.float64(0.008668311550706164)),
 (359, np.float64(0.0)),
 (360, np.float64(0.017953160345580043)),
 (361, np.float64(0.0)),
 (362, np.float64(0.03166834779008205)),
 (363, np.float64(0.006637103391835837)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.0)),
 (373, np.float64(0.07112394697975578)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.011407564144343877)),
 (386, np.float64(0.0)),
 (387, np.float64(0.0)),
 (388, np.float64(0.0)),
 (389, np.float64(0.014382221127457503)),
 (390, np.float64(0.009518669504911264)),
 (391, np.float64(0.010338566571052935)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.0)),
 (395, np.float64(0.023744536615487158)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.021640428173372625)),
 (401, np.float64(0.04116784642875)),
 (402, np.float64(0.010848228649015888)),
 (403, np.float64(0.007522745564060013)),
 (404, np.float64(0.06030226569885218)),
 (405, np.float64(0.035806187126134044)),
 (406, np.float64(0.005450345122455705)),
 (407, np.float64(0.0)),
 (408, np.float64(0.00943408436948973)),
 (409, np.float64(0.00649252029116795)),
 (410, np.float64(0.022792184308144295)),
 (411, np.float64(0.0)),
 (412, np.float64(0.0200452665286035)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.016649932651121663)),
 (419, np.float64(0.03489914389791733)),
 (420, np.float64(0.035787861690470546)),
 (421, np.float64(0.0)),
 (422, np.float64(0.013534774420783956)),
 (423, np.float64(0.0)),
 (424, np.float64(0.034264287563403384)),
 (425, np.float64(0.0)),
 (426, np.float64(0.035841745790640284)),
 (427, np.float64(0.0)),
 (428, np.float64(0.00881395376729767)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.02480344523639407)),
 (433, np.float64(0.0)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0406773490542124)),
 (440, np.float64(0.006149877872062611)),
 (441, np.float64(0.008310766329020815)),
 (442, np.float64(0.0)),
 (443, np.float64(0.048233119854634424)),
 (444, np.float64(0.01517739651407271)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.012290686404449021)),
 (448, np.float64(0.020485159072648758)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.06061066997406978)),
 (455, np.float64(0.0)),
 (456, np.float64(0.015086950229015695)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.018771137266414384)),
 (462, np.float64(0.03397453798799191)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0)),
 (473, np.float64(0.05849726730091015)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0)),
 (476, np.float64(0.010325034050201427)),
 (477, np.float64(0.016722562376129055)),
 (478, np.float64(0.010020389555722492)),
 (479, np.float64(0.00453351923752785)),
 (480, np.float64(0.020786849919204986)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.009022689106186584)),
 (487, np.float64(0.06275480086880951)),
 (488, np.float64(0.0)),
 (489, np.float64(0.011058500719038945)),
 (490, np.float64(0.0)),
 (491, np.float64(0.017190690781164652)),
 (492, np.float64(0.0)),
 (493, np.float64(0.020962975284714833)),
 (494, np.float64(0.0)),
 (495, np.float64(0.0)),
 (496, np.float64(0.010490520313642827)),
 (497, np.float64(0.0)),
 (498, np.float64(0.009074127017110283)),
 (499, np.float64(0.0)),
 (500, np.float64(0.05508082020613065)),
 (501, np.float64(0.008240613504248779)),
 (502, np.float64(0.03012948946746212)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0)),
 (505, np.float64(0.03328763225618516)),
 (506, np.float64(0.0)),
 (507, np.float64(0.014191435701753024)),
 (508, np.float64(0.012580275044897418)),
 (509, np.float64(0.028058077465183816)),
 (510, np.float64(0.008798340039474935)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.0)),
 (515, np.float64(0.02149129732384898)),
 (516, np.float64(0.0)),
 (517, np.float64(0.020812032843081626)),
 (518, np.float64(0.02649104953721125)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.005653536898355653)),
 (524, np.float64(0.014820667329577507)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.05952690460008954)),
 (530, np.float64(0.0)),
 (531, np.float64(0.021726289408211467)),
 (532, np.float64(0.011810503512878805)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.0)),
 (536, np.float64(0.0)),
 (537, np.float64(0.03377902642044296)),
 (538, np.float64(0.0)),
 (539, np.float64(0.03572180516147093)),
 (540, np.float64(0.0)),
 (541, np.float64(0.03323299762497831)),
 (542, np.float64(0.008835340675404414)),
 (543, np.float64(0.005596517067855569)),
 (544, np.float64(0.020366453236280717)),
 (545, np.float64(0.01555725652136555)),
 (546, np.float64(0.009686662719229003)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.0)),
 (550, np.float64(0.013101223367845674)),
 (551, np.float64(0.0)),
 (552, np.float64(0.01434179096939347)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.01950518411413811)),
 (556, np.float64(0.0)),
 (557, np.float64(0.010049499818067659)),
 (558, np.float64(0.0)),
 (559, np.float64(0.0)),
 (560, np.float64(0.0)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.02998913345697007)),
 (564, np.float64(0.024755682723938945)),
 (565, np.float64(0.0)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.007779224761962552)),
 (569, np.float64(0.0)),
 (570, np.float64(0.0)),
 (571, np.float64(0.01566136138668507)),
 (572, np.float64(0.0)),
 (573, np.float64(0.031029998052109386)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.008472125011248707)),
 (577, np.float64(0.0)),
 (578, np.float64(0.0)),
 (579, np.float64(0.022573111976213114)),
 (580, np.float64(0.0)),
 (581, np.float64(0.0900594125581888)),
 (582, np.float64(0.02283661362899101)),
 (583, np.float64(0.0)),
 (584, np.float64(0.0)),
 (585, np.float64(0.020808377614610907)),
 (586, np.float64(0.0060893260762652545)),
 (587, np.float64(0.02219851809042213)),
 (588, np.float64(0.02997208608157952)),
 (589, np.float64(0.0)),
 (590, np.float64(0.0)),
 (591, np.float64(0.00875961739639285)),
 (592, np.float64(0.04403661344701933)),
 (593, np.float64(0.0)),
 (594, np.float64(0.0)),
 (595, np.float64(0.03733671458175879)),
 (596, np.float64(0.012301153523295704)),
 (597, np.float64(0.0)),
 (598, np.float64(0.0)),
 (599, np.float64(0.005745275971666855)),
 (600, np.float64(0.0262104603548376)),
 (601, np.float64(0.0)),
 (602, np.float64(0.020774410692259423)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.021526892991432137)),
 (607, np.float64(0.04538169103402193)),
 (608, np.float64(0.0)),
 (609, np.float64(0.029938076466136387)),
 (610, np.float64(0.015169864172183698)),
 (611, np.float64(0.0)),
 (612, np.float64(0.011497175489593238)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.0)),
 (618, np.float64(0.020077916279963443)),

In [11]:
scores = sorted(scores, key=lambda x: x[1], reverse=True)

In [12]:
movies_indices = [tpl[0] for tpl in scores[1:4]]
movies_indices

[1254, 4161, 2932]

In [13]:
list(movies["title"].iloc[movies_indices])

['Get Carter', 'The Marine 4: Moving Target', 'Raising Cain']

In [14]:
def similar_movies(movie_title, nr_movies):
    idx = movies.loc[movies["title"]==movie_title].index[0]
    scores = list(enumerate(similarity_matrix[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    movies_indices = [tpl[0] for tpl in scores[1:nr_movies+1]]
    similar_titles = list(movies["title"].iloc[movies_indices])
    return similar_titles

In [15]:
similar_movies("Kung Fu Panda 3", 3)

['Kung Fu Panda 2',
 'My Big Fat Greek Wedding 2',
 'Once Upon a Time in the West']

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=63b8260d-65e2-41bc-8890-d88a99f8ec78' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>